ROS_VARS="-e ROS_MASTER_URI=$ROS_MASTER_URI -e ROS_IP=$ROS_IP -e ROS_DOMAIN_ID=$ROS_DOMAIN_ID"
KIMERA_VARS="-e CAMERA=$KIMERA_VIO_CAMERA -e ROBOT_NAME=$ROBOT_NAME"

docker run -it --rm --net=host \
	$ROS_VARS $KIMERA_VARS \
	kimera-vio-docker
